package checks

import (
	"go/ast"
	"go/types"

	"golang.org/x/tools/go/analysis"

	"github.com/jxsl13/perfscan/perfscan/internal/astutil"
	"github.com/jxsl13/perfscan/perfscan/lint"
)

// PS2032 reports string(strconv.AppendInt(nil, ...)) and its
// Append*/Quote* siblings — formatting into a throwaway byte slice and
// converting it to a string — when the matching strconv.Format*/Quote*
// function produces the identical string directly. The exact mirror of
// PS2136: there the desired result is []byte, so Append*(nil, ...) beats
// []byte(Format*(...)); here the desired result is a string, so
// Format*(...) beats string(Append*(nil, ...)).
var PS2032 = register(&lint.Check{
	ID:       "PS2032",
	Category: "alloc",
	Slug:     "strconv-format-string",
	Level:    lint.LevelIdiomatic,
	AutoFix:  true,
	Doc: lint.Documentation{
		Title: "string(strconv.AppendInt(nil, ...)) allocates a throwaway []byte then copies it; strconv.FormatInt formats the string directly",
		Text: `strconv.AppendInt(nil, x, 10) appends to the nil slice, which heap-
allocates a fresh byte slice for the digits; the surrounding string(...)
conversion then COPIES those bytes into a second heap allocation for the
string. strconv.FormatInt(x, 10) produces the identical string in one
step — and for small integers (0 <= i < 100 in base 10, and every
single-digit value in any base) it returns a substring of a package
constant with ZERO allocations. The rewrite drops from two allocations
plus a copy to one or zero allocations; the saved copy is O(len) of the
formatted text. Every strconv Append* function has a Format*/Quote* twin
— in the standard library the Append form IS the append of the Format
form's bytes — so the mapping is uniform:

  string(strconv.AppendInt(nil, x, b))          -> strconv.FormatInt(x, b)
  string(strconv.AppendUint(nil, x, b))         -> strconv.FormatUint(x, b)
  string(strconv.AppendFloat(nil, f, m, p, s))  -> strconv.FormatFloat(f, m, p, s)
  string(strconv.AppendBool(nil, v))            -> strconv.FormatBool(v)
  string(strconv.AppendQuote(nil, s))           -> strconv.Quote(s)       (and the
                                                   QuoteToASCII/QuoteToGraphic/
                                                   QuoteRune* variants likewise)

The rewrite is BIT-IDENTICAL under the fix's gates. strconv documents
each Append* as appending the string form "as generated by" its Format*
twin, so the appended bytes ARE Format*'s bytes, and string() of them is
Format*'s string byte-for-byte — for every value, base, float verb
(including unrecognized verbs, which both sides render as '%'+verb),
precision, bitSize, invalid-UTF-8 quote input, and invalid rune. Both
forms evaluate every argument exactly once in the same order, and both
panic identically on an illegal integer base (the panic is raised by the
shared formatter). PS2109/PS2136's nil-vs-empty hazard does not exist in
this direction: string(b) maps nil and empty []byte to the same "", and
these formatters never produce empty output anyway.

Two gates keep the rewrite exact. The destination argument must be the
LITERAL untyped nil (a shadowed identifier named nil, or any non-nil
buffer expression, would prepend that buffer's bytes — those shapes are
not matched at all). And the conversion target's handling depends on its
spelling: the predeclared string(...) conversion (or an alias of it) is
removed outright, while a NAMED string type keeps its conversion wrapper
around the Format* call — T(string) is exactly as legal as T([]byte) for
any T whose underlying type is string, and yields the same value — so
the rewrite always type-checks. The fix edits around the call: only the
selected name changes (AppendInt -> FormatInt, keeping an aliased
strconv qualifier, so the import can never be orphaned) and the nil
argument is deleted; every remaining argument carries over verbatim, in
place. A comment inside any deleted region withholds the fix and keeps
the advisory report.`,
		Before: `s := string(strconv.AppendInt(nil, x, 10))`,
		After:  `s := strconv.FormatInt(x, 10)`,
		MeasuredWin: `BenchmarkPS2032 (6-digit int64, Apple M2 Pro, go1.26):
string(strconv.AppendInt(nil, x, 10)) 36.9 ns/op, 16 B/op, 2 allocs/op
-> strconv.FormatInt(x, 10) 19.1 ns/op, 8 B/op, 1 alloc/op (~1.9x, half
the allocations and bytes); on FormatInt's small-integer constant-table
path the same rewrite is allocation-FREE: 22.3 ns/op, 8 B/op, 1 alloc/op
-> 2.7 ns/op, 0 B/op, 0 allocs/op (~8x).`,
	},
	Analyzer: &analysis.Analyzer{
		Name: "PS2032",
		Doc:  "string(strconv.Append*(nil, ...)) instead of strconv.Format*/Quote*(...)",
		Run:  runPS2032,
	},
})

// ps2032Verb maps a matched strconv Append* function to its direct
// Format*/Quote* twin and its (fixed, non-variadic) parameter count
// INCLUDING the destination slice.
type ps2032Verb struct {
	formatName string
	argc       int
}

var ps2032Format = map[string]ps2032Verb{
	"AppendInt":                {"FormatInt", 3},
	"AppendUint":               {"FormatUint", 3},
	"AppendFloat":              {"FormatFloat", 5},
	"AppendBool":               {"FormatBool", 2},
	"AppendQuote":              {"Quote", 2},
	"AppendQuoteToASCII":       {"QuoteToASCII", 2},
	"AppendQuoteToGraphic":     {"QuoteToGraphic", 2},
	"AppendQuoteRune":          {"QuoteRune", 2},
	"AppendQuoteRuneToASCII":   {"QuoteRuneToASCII", 2},
	"AppendQuoteRuneToGraphic": {"QuoteRuneToGraphic", 2},
}

func runPS2032(pass *analysis.Pass) (any, error) {
	for _, f := range pass.Files {
		ast.Inspect(f, func(n ast.Node) bool {
			outer, ok := n.(*ast.CallExpr)
			if !ok || len(outer.Args) != 1 || outer.Ellipsis.IsValid() {
				return true
			}
			// plain=true: the predeclared string type (or an alias of it),
			// whose conversion shell the fix removes; plain=false: a named
			// string type, whose shell the fix keeps.
			plain, isConv := ps2032StringConv(pass, outer)
			if !isConv {
				return true
			}
			call, ok := ps2109Unparen(outer.Args[0]).(*ast.CallExpr)
			if !ok || call.Ellipsis.IsValid() {
				return true
			}
			name, ok := astutil.PkgFuncCall(pass.TypesInfo, call.Fun, "strconv", nil)
			if !ok {
				return true
			}
			verb, known := ps2032Format[name]
			if !known || len(call.Args) != verb.argc {
				return true
			}
			// The destination must be the LITERAL untyped nil: a non-nil
			// buffer would prepend its bytes, and even an identifier NAMED
			// nil can be a shadowing variable holding one.
			if !ps2032IsUntypedNil(pass, call.Args[0]) {
				return true
			}
			diag := analysis.Diagnostic{
				Pos: outer.Pos(),
				End: outer.End(),
				Message: "string(strconv." + name + "(nil, ...)) formats into a throwaway []byte and copies it into a string; strconv." +
					verb.formatName + "(...) formats the identical string directly",
			}
			// PkgFuncCall matched, so call.Fun is a SelectorExpr whose
			// qualifier resolves to strconv; the rename keeps that
			// (possibly aliased) qualifier from the source untouched.
			sel := call.Fun.(*ast.SelectorExpr)
			// Deleted regions must not swallow a comment: the nil argument
			// (up to the following argument) always goes; the conversion
			// shell goes only in the plain-string case.
			commented := ps2109CommentBetween(f, call.Args[0].Pos(), call.Args[1].Pos())
			if plain {
				commented = commented ||
					ps2109CommentBetween(f, outer.Pos(), call.Pos()) ||
					ps2109CommentBetween(f, call.End(), outer.End())
			}
			if !commented {
				edits := []analysis.TextEdit{
					// Rename AppendX -> FormatX/QuoteX, keeping the (possibly
					// aliased) qualifier and every other argument untouched ...
					{Pos: sel.Sel.Pos(), End: sel.Sel.End(), NewText: []byte(verb.formatName)},
					// ... and drop the nil destination (through the start of
					// the next argument, taking the comma and spacing along).
					{Pos: call.Args[0].Pos(), End: call.Args[1].Pos()},
				}
				if plain {
					// Drop the "string(" shell (with any wrapping parens) and
					// its closing ")": the call's own string result replaces
					// the conversion. A NAMED string target keeps its shell —
					// T(string) is as legal as T([]byte) and yields the same
					// value — so the rewrite always type-checks.
					edits = append(edits,
						analysis.TextEdit{Pos: outer.Pos(), End: call.Pos()},
						analysis.TextEdit{Pos: call.End(), End: outer.End()},
					)
				}
				diag.SuggestedFixes = []analysis.SuggestedFix{{
					Message:   "replace with strconv." + verb.formatName + "(...)",
					TextEdits: edits,
				}}
			}
			pass.Report(diag)
			return true
		})
	}
	return nil, nil
}

// ps2032StringConv reports whether call is a conversion to a string type:
// plain=true for the predeclared string (or an alias of it), plain=false
// for a named type whose underlying type is string. Type information
// distinguishes a conversion from a function call and sees through a
// shadowed string identifier. Type parameters are never matched (their
// conversion semantics depend on the instantiation).
func ps2032StringConv(pass *analysis.Pass, call *ast.CallExpr) (plain, ok bool) {
	tv, ok := pass.TypesInfo.Types[call.Fun]
	if !ok || !tv.IsType() {
		return false, false
	}
	switch t := types.Unalias(tv.Type).(type) {
	case *types.Basic:
		return true, t.Kind() == types.String
	case *types.Named:
		b, isBasic := t.Underlying().(*types.Basic)
		return false, isBasic && b.Kind() == types.String
	}
	return false, false
}

// ps2032IsUntypedNil reports whether e is (a parenthesization of) the
// predeclared nil identifier. An identifier merely NAMED nil that
// resolves to a shadowing declaration is rejected — as a []byte variable
// it could carry bytes that Append* would prepend.
func ps2032IsUntypedNil(pass *analysis.Pass, e ast.Expr) bool {
	id, ok := ps2109Unparen(e).(*ast.Ident)
	if !ok || id.Name != "nil" {
		return false
	}
	_, isNil := pass.TypesInfo.Uses[id].(*types.Nil)
	return isNil
}
