// Command gendocs renders the check registry into docs/checks/ — one
// markdown page per check plus an index. Run via `make docs`; CI fails if
// the rendered docs drift from the registry.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jxsl13/perfscan/perfscan/checks"
	"github.com/jxsl13/perfscan/perfscan/lint"
)

func main() {
	outDir := "docs/checks"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}

	for _, c := range checks.All() {
		page := renderCheckPage(c)
		if err := os.WriteFile(filepath.Join(outDir, c.ID+".md"), []byte(page), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "gendocs:", err)
			os.Exit(1)
		}
	}
	if err := os.WriteFile(filepath.Join(outDir, "README.md"), []byte(renderIndex()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
	fmt.Printf("gendocs: wrote %d check pages to %s\n", len(checks.All()), outDir)
}

// renderIndex returns the docs/checks/README.md content. Kept pure (no I/O) so a
// docs-sync test can compare it to the committed file.
func renderIndex() string {
	var index strings.Builder
	index.WriteString(`# perfscan checks

<!-- Generated by gendocs; do not edit. Run make docs. -->

Every check has a stable PS-prefixed ID and a fix level:
**L1** idiomatic (mechanical, bit-identical),
**L2** structured (restructuring),
**L3** aggressive (hyper-optimization). One ` + "`-level`" + ` knob gates both
reporting and fixing: ` + "`perfscan -fix`" + ` applies exactly the reported
checks' fixes.

| ID | Category | Level | Auto-fix | Title |
|----|----------|-------|----------|-------|
`)
	for _, c := range checks.All() {
		fix := ""
		if c.AutoFix {
			fix = "yes"
		}
		fmt.Fprintf(&index, "| [%s](%s.md) | %s | %s | %s | %s |\n",
			c.ID, c.ID, c.Category, c.Level, fix, c.Doc.Title)
	}
	return index.String()
}

// renderCheckPage returns the docs/checks/<ID>.md content for a check. Kept pure
// (no I/O) so a docs-sync test can compare it to the committed file.
func renderCheckPage(c *lint.Check) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — %s\n\n<!-- Generated by gendocs; do not edit. Run make docs. -->\n\n", c.ID, c.Slug)
	fmt.Fprintf(&b, "**%s**\n\n", c.Doc.Title)
	fmt.Fprintf(&b, "- Category: `%s`\n- Fix level: **%s**\n", c.Category, c.Level)
	if c.AutoFix {
		b.WriteString("- Auto-fix: **yes** (deterministic, bit-identical)\n")
	} else {
		b.WriteString("- Auto-fix: no (advisory)\n")
	}
	if c.NeedsConfig {
		fmt.Fprintf(&b, "- Domain check: requires vocabulary `%s` in perfscan.yaml\n", strings.Join(c.Vocab, "`, `"))
	}
	b.WriteByte('\n')
	b.WriteString(strings.TrimSpace(c.Doc.Text))
	b.WriteByte('\n')
	if c.Doc.Before != "" {
		fmt.Fprintf(&b, "\n## Example\n\nBefore:\n\n```go\n%s\n```\n\nAfter:\n\n```go\n%s\n```\n", c.Doc.Before, c.Doc.After)
	}
	if c.Doc.MeasuredWin != "" {
		fmt.Fprintf(&b, "\n## Measured\n\n%s\n", c.Doc.MeasuredWin)
	}
	fmt.Fprintf(&b, "\n## Suppressing\n\n```go\n//perfscan:ignore %s <reason>\n```\n", c.ID)
	return b.String()
}
