package runner

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/jxsl13/perfscan/checks"
	"github.com/jxsl13/perfscan/lint"
)

// collectBody is an append-without-prealloc shape that reliably fires PS2101.
func ps2101Body(fn string) string {
	return "func " + fn + `(src []string) []string {
	out := []string{}
	for _, s := range src {
		out = append(out, s)
	}
	return out
}
`
}

// TestRunFilterComposition pins the file-level finding-filter contract through
// the real Run() pipeline: generated files are skipped by default,
// -include-generated brings them back, -exclude removes matching paths, and
// -exclude wins over -include-generated for the same file. A reordering of the
// filter stages in Run() would break one of these.
func TestRunFilterComposition(t *testing.T) {
	dir := t.TempDir()
	write := func(rel, content string) {
		p := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("go.mod", "module corpus\n\ngo 1.23\n")
	write("normal.go", "package corpus\n\n"+ps2101Body("normalCollect"))
	write("zz_generated.go", "// Code generated by tool; DO NOT EDIT.\n\npackage corpus\n\n"+ps2101Body("genCollect"))
	write("sub/excluded.go", "package sub\n\n"+ps2101Body("subCollect"))

	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer func() { _ = os.Chdir(wd) }()

	run := func(opts Options) string {
		var out, errBuf bytes.Buffer
		opts.Patterns = []string{"./..."}
		opts.MaxLevel = lint.LevelAggressive
		opts.Stdout = &out
		opts.Stderr = &errBuf
		Run(checks.All(), opts)
		return out.String() + errBuf.String()
	}
	has := func(s, sub string) bool { return bytes.Contains([]byte(s), []byte(sub)) }

	t.Run("default: generated skipped, others reported", func(t *testing.T) {
		o := run(Options{})
		if !has(o, "normal.go") {
			t.Errorf("normal.go finding should be reported:\n%s", o)
		}
		if !has(o, filepath.Join("sub", "excluded.go")) && !has(o, "sub/excluded.go") {
			t.Errorf("sub/excluded.go finding should be reported (no -exclude):\n%s", o)
		}
		if has(o, "zz_generated.go") {
			t.Errorf("generated file must be skipped by default:\n%s", o)
		}
		if !has(o, "generated files skipped") {
			t.Errorf("expected the generated-skip note on stderr:\n%s", o)
		}
	})

	t.Run("-exclude removes matching path", func(t *testing.T) {
		o := run(Options{Exclude: []string{"sub/"}})
		if has(o, "excluded.go") {
			t.Errorf("-exclude sub/ must drop sub/excluded.go:\n%s", o)
		}
		if !has(o, "normal.go") {
			t.Errorf("normal.go should still be reported under -exclude sub/:\n%s", o)
		}
	})

	t.Run("-include-generated brings generated back", func(t *testing.T) {
		o := run(Options{IncludeGenerated: true})
		if !has(o, "zz_generated.go") {
			t.Errorf("-include-generated must report the generated file:\n%s", o)
		}
	})

	t.Run("-exclude wins over -include-generated for same file", func(t *testing.T) {
		o := run(Options{IncludeGenerated: true, Exclude: []string{"zz_generated"}})
		if has(o, "zz_generated.go") {
			t.Errorf("-exclude must drop the file even with -include-generated:\n%s", o)
		}
		if !has(o, "normal.go") {
			t.Errorf("normal.go should remain:\n%s", o)
		}
	})
}
