package runner

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsGeneratedSource(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{"cgo header", "// Code generated by cmd/cgo; DO NOT EDIT.\n\n//line x.go:1\npackage main\n", true},
		{"stringer", "// Code generated by \"stringer\"; DO NOT EDIT.\npackage p\n", true},
		{"leading blank/comment then marker", "\n// unrelated\n// Code generated by tool; DO NOT EDIT.\npackage p\n", true},
		{"plain file", "package p\n\nfunc f() {}\n", false},
		{"marker AFTER package is not generated", "package p\n// Code generated by x; DO NOT EDIT.\n", false},
		{"similar but not the marker", "// Code generated by x (no do-not-edit)\npackage p\n", false},
		{"empty", "", false},
	}
	for _, c := range cases {
		if got := isGeneratedSource([]byte(c.src)); got != c.want {
			t.Errorf("%s: isGeneratedSource = %v, want %v", c.name, got, c.want)
		}
	}
}

func TestOutsideWorkTree(t *testing.T) {
	// A path inside a fresh temp dir is writable; one under GOCACHE is not.
	local := filepath.Join(t.TempDir(), "pkg", "a.go")
	if outsideWorkTree(local) {
		t.Errorf("%s should be inside the work tree", local)
	}
	cache := os.Getenv("GOCACHE")
	if cache == "" {
		if d, err := os.UserCacheDir(); err == nil {
			cache = filepath.Join(d, "go-build")
		}
	}
	if cache != "" {
		cached := filepath.Join(cache, "ab", "cdef-d")
		if !outsideWorkTree(cached) {
			t.Errorf("%s should be flagged outside the work tree (GOCACHE=%s)", cached, cache)
		}
	}
	// A sibling of a forbidden root whose name shares a prefix must NOT match.
	if len(forbiddenWriteRoots) > 0 {
		sibling := forbiddenWriteRoots[0] + "-not-really/x.go"
		if outsideWorkTree(sibling) {
			t.Errorf("%s must not be treated as under %s (prefix, not subtree)", sibling, forbiddenWriteRoots[0])
		}
	}
}
