package closureenv

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

// Portable identities are source-observed package+relative-file names and
// module-path manifests, not user-supplied dependency hashes. Content and
// selected tests/native/embed inputs still participate, including the SDK.
func binaryPortableMaterialDigest(output []byte) ([32]byte, error) {
	inputs := map[string][32]byte{}
	add := func(identity, path string) error {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		digest := sha256.Sum256(data)
		if old, ok := inputs[identity]; ok && old != digest {
			return errors.New("conflicting portable material identity")
		}
		inputs[identity] = digest
		return nil
	}
	decoder := json.NewDecoder(bytes.NewReader(output))
	for decoder.More() {
		var pkg struct {
			listedBinaryPackage
			Name   string
			Module *struct {
				Dir, GoMod, Path, Version, GoVersion string
				Replace                              *struct{ Path string }
			}
		}
		if err := decoder.Decode(&pkg); err != nil {
			return [32]byte{}, err
		}
		if len(pkg.CgoFiles) != 0 || pkg.Module != nil && pkg.Module.Replace != nil {
			return [32]byte{}, errors.New("portable cgo/replacement inputs unsupported")
		}
		var selectionText strings.Builder
		selectionText.Grow(128)
		selectionText.WriteString("standard=" + strconv.FormatBool(pkg.Standard) + ";goroot=" + strconv.FormatBool(pkg.Goroot))
		if pkg.Module != nil {
			selectionText.WriteString(";module=" + pkg.Module.Path + ";version=" + pkg.Module.Version + ";go=" + pkg.Module.GoVersion)
		}
		selectionKey := "selection:" + pkg.ImportPath
		selectionDigest := sha256.Sum256([]byte(selectionText.String()))
		if old, ok := inputs[selectionKey]; ok && old != selectionDigest {
			return [32]byte{}, errors.New("conflicting portable package selection")
		}
		inputs[selectionKey] = selectionDigest
		for _, name := range slices.Concat(pkg.GoFiles, pkg.TestGoFiles, pkg.XTestGoFiles, pkg.SFiles, pkg.CFiles, pkg.CXXFiles, pkg.MFiles, pkg.HFiles, pkg.FFiles, pkg.SysoFiles, pkg.EmbedFiles, pkg.TestEmbedFiles, pkg.XTestEmbedFiles) {
			path := name
			identity := name
			if !filepath.IsAbs(path) {
				path = filepath.Join(pkg.Dir, path)
			} else {
				relative, err := filepath.Rel(pkg.Dir, path)
				if err != nil {
					return [32]byte{}, err
				}
				if filepath.IsLocal(relative) {
					identity = relative
				} else {
					// The selected go command emits a synthetic test main in its
					// action cache. -trimpath fixes package identities while the
					// cache filename is location-dependent; retain exact content.
					data, err := os.ReadFile(path)
					if err != nil {
						return [32]byte{}, err
					}
					if pkg.Name != "main" || !strings.HasSuffix(pkg.ImportPath, ".test") || len(pkg.GoFiles) != 1 || name != pkg.GoFiles[0] || !bytes.Contains(data, []byte("// Code generated by 'go test'. DO NOT EDIT.")) {
						return [32]byte{}, errors.New("unqualified external portable input location")
					}
					identity = "generated-test-main.go"
				}
			}
			if err := add("package:"+pkg.ImportPath+":"+filepath.ToSlash(identity), path); err != nil {
				return [32]byte{}, err
			}
		}
		if pkg.Module != nil && pkg.Module.GoMod != "" {
			if pkg.Module.Path == "" {
				return [32]byte{}, errors.New("missing observed module identity")
			}
			if err := add("module:"+pkg.Module.Path+"@"+pkg.Module.Version+":go.mod", pkg.Module.GoMod); err != nil {
				return [32]byte{}, err
			}
			sum := filepath.Join(pkg.Module.Dir, "go.sum")
			if _, err := os.Stat(sum); err == nil {
				if err := add("module:"+pkg.Module.Path+"@"+pkg.Module.Version+":go.sum", sum); err != nil {
					return [32]byte{}, err
				}
			} else if !os.IsNotExist(err) {
				return [32]byte{}, err
			}
		}
	}
	names := make([]string, 0, len(inputs))
	for name := range inputs {
		names = append(names, name)
	}
	slices.Sort(names)
	hash := sha256.New()
	for _, name := range names {
		_, _ = io.WriteString(hash, name)
		_, _ = hash.Write([]byte{0})
		digest := inputs[name]
		_, _ = hash.Write(digest[:])
		_, _ = hash.Write([]byte{0})
	}
	var digest [32]byte
	copy(digest[:], hash.Sum(nil))
	return digest, nil
}
