package closureenv

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestPortableMaterialExternalTestMain(t *testing.T) {
	t.Parallel()
	root, cache := t.TempDir(), t.TempDir()
	generated := filepath.Join(cache, "action-cache-entry")
	const source = "// Code generated by 'go test'. DO NOT EDIT.\npackage main\nfunc main() {}\n"
	if err := os.WriteFile(generated, []byte(source), 0600); err != nil {
		t.Fatal(err)
	}
	collect := func(t *testing.T, change func(map[string]any)) ([32]byte, error) {
		t.Helper()
		pkg := map[string]any{"Name": "main", "ImportPath": "example.test/input.test", "Dir": root, "GoFiles": []string{generated}}
		if change != nil {
			change(pkg)
		}
		data, err := json.Marshal(pkg)
		if err != nil {
			t.Fatal(err)
		}
		return binaryPortableMaterialDigest(data)
	}
	baseline, err := collect(t, nil)
	if err != nil {
		t.Fatal(err)
	}
	t.Run("different Windows volume", func(t *testing.T) {
		t.Parallel()
		if runtime.GOOS != "windows" {
			t.Skip("cross-volume filepath.Rel behavior is Windows-specific")
		}
		volume := "Z:"
		if strings.EqualFold(filepath.VolumeName(generated), volume) {
			volume = "Y:"
		}
		otherRoot := volume + `\source\package`
		if _, err := filepath.Rel(otherRoot, generated); err == nil {
			t.Fatal("cross-volume regression did not exercise Rel failure")
		}
		got, err := collect(t, func(pkg map[string]any) { pkg["Dir"] = otherRoot })
		if err != nil || got != baseline {
			t.Fatalf("cross-volume generated main changed portable identity: %x, %v", got, err)
		}
	})
	for _, tc := range []struct {
		name   string
		change func(map[string]any)
	}{
		{"not main", func(pkg map[string]any) { pkg["Name"] = "input" }},
		{"not test binary", func(pkg map[string]any) { pkg["ImportPath"] = "example.test/input" }},
		{"multiple Go inputs", func(pkg map[string]any) { pkg["GoFiles"] = []string{generated, generated} }},
		{"different input role", func(pkg map[string]any) {
			pkg["GoFiles"] = []string{}
			pkg["TestGoFiles"] = []string{generated}
		}},
		{"relative package root", func(pkg map[string]any) { pkg["Dir"] = "relative-package-root" }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if _, err := collect(t, tc.change); err == nil {
				t.Fatal("unqualified external material accepted")
			}
		})
	}
	t.Run("exact content remains bound", func(t *testing.T) {
		t.Parallel()
		changed := filepath.Join(t.TempDir(), "other-action-cache-entry")
		if err := os.WriteFile(changed, []byte(source+"// changed generated instrumentation\n"), 0600); err != nil {
			t.Fatal(err)
		}
		got, err := collect(t, func(pkg map[string]any) { pkg["GoFiles"] = []string{changed} })
		if err != nil || got == baseline {
			t.Fatalf("changed generated content escaped binding: %x, %v", got, err)
		}
	})
	t.Run("unmarked external input", func(t *testing.T) {
		t.Parallel()
		unmarked := filepath.Join(t.TempDir(), "external.go")
		if err := os.WriteFile(unmarked, []byte("package main\nfunc main() {}\n"), 0600); err != nil {
			t.Fatal(err)
		}
		if _, err := collect(t, func(pkg map[string]any) { pkg["GoFiles"] = []string{unmarked} }); err == nil {
			t.Fatal("unmarked external source accepted as generated test main")
		}
	})
}
