// Package crossover records source-bound dispatch evidence. Fresh evidence is
// not an automatic profitability decision or a production threshold rewrite.
package crossover

import (
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"slices"
	"strconv"
	"strings"

	"github.com/jxsl13/perfscan/config"
)

const HarnessFile = "perfscan_crossover_diagnostic_test.go"

// HarnessModel is produced by the typed source checker, never decoded from an
// evidence artifact. Bodies are exact formatted copies differing only at the
// independently identified dispatch predicate. Extents/guards are expressions
// derived from the actual operation's typed output and dtype dispatch.
type HarnessModel struct {
	Boundary                                                  int64
	Package, PackagePath, Signature, SerialBody, ParallelBody string
	Imports                                                   map[string]string
	SourceSHA256                                              map[string]string
	TypedFileSHA256                                           map[string]string
	TypedPackageFiles                                         map[string][]string
	OriginalSizes                                             []int
	ArgumentCount, ResultCount                                int
	ErrorResults                                              []int
	OutputExtent, InputData, DtypeGuard                       string
	OutputData, OutputGuard                                   string
	Dtype                                                     string
	WorkerCallback                                            bool
}

func local(path, name string) (string, error) {
	name, ok := strings.CutPrefix(name, path+".")
	if !ok || !token.IsIdentifier(name) {
		return "", errors.New("harness selectors must be exact package-local identifiers")
	}
	return name, nil
}

// Generate renders a deterministic diagnostic-only harness. The scanner must
// regenerate it from CURRENT typed production source, not trust its digest.
func Generate(m *HarnessModel, c *config.DispatchCrossoverContract) ([]byte, error) {
	if m == nil || c == nil || !token.IsIdentifier(m.Package) || m.Dtype != "float32" && m.Dtype != "float64" || m.ArgumentCount < 1 || m.ResultCount < 1 || m.OutputExtent == "" || m.InputData == "" || m.OutputData == "" || m.OutputGuard == "" {
		return nil, errors.New("unsupported typed operation harness")
	}
	names := make([]string, 0, 7)
	for _, name := range []string{c.SerialPolicy, c.WorkerRunner, c.SerialOperation, c.ParallelOperation, c.DispatchFunction, c.OperationInputFactory, c.DiagnosticFunction} {
		if name == "" {
			names = append(names, "")
			continue
		}
		n, err := local(m.PackagePath, name)
		if err != nil {
			return nil, err
		}
		names = append(names, n)
	}
	leaf, worker, serial, parallel, production, factory, diagnostic := names[0], names[1], names[2], names[3], names[4], names[5], names[6]
	if serial != "" && (serial == parallel || serial == production) || parallel != "" && parallel == production || !strings.HasPrefix(diagnostic, "Test") {
		return nil, errors.New("diagnostic operation copies must have distinct names and a Test entry")
	}
	// Always use reserved test-only copy names, never overwrite any configured
	// existing operation/helper declaration in production or committed tests.
	serial = "_perfscanCrossoverSerial"
	parallel = "_perfscanCrossoverParallel"
	imports := make(map[string]string, len(m.Imports)+8)
	for path, alias := range m.Imports {
		imports[path] = alias
	}
	aliases := make(map[string]string, 8)
	for _, path := range []string{"encoding/json", "fmt", "math", "os", "runtime", "strconv", "testing", "github.com/jxsl13/perfscan/benchmarkevidence"} {
		alias := imports[path]
		if alias == "" {
			alias = "_ps" + path[strings.LastIndexByte(path, '/')+1:]
			imports[path] = alias
		}
		if alias == "_" || alias == "." {
			return nil, errors.New("diagnostic harness cannot reproduce blank/dot package qualification")
		}
		aliases[path] = alias
	}
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	slices.Sort(paths)
	var source strings.Builder
	fmt.Fprintf(&source, "// Code generated by perfscan-crossover from typed production source; DO NOT EDIT.\n// Forced-route copies are diagnostic instrumentation, not unmodified production timing.\npackage %s\nimport (\n", m.Package)
	for _, path := range paths {
		fmt.Fprintf(&source, "%s %s\n", imports[path], strconv.Quote(path))
	}
	source.WriteString(")\n")
	fmt.Fprintf(&source, "func %s%s %s\nfunc %s%s %s\n", serial, strings.TrimPrefix(m.Signature, "func"), m.SerialBody, parallel, strings.TrimPrefix(m.Signature, "func"), m.ParallelBody)
	args := make([]string, m.ArgumentCount)
	for i := range args {
		args[i] = "_arg" + strconv.Itoa(i)
	}
	results := make([]string, m.ResultCount)
	for i := range results {
		results[i] = "_r" + strconv.Itoa(i)
	}
	var errorsCheck strings.Builder
	for _, i := range m.ErrorResults {
		fmt.Fprintf(&errorsCheck, "if _r%d != nil { b.Fatal(_r%d) };\n", i, i)
	}
	output := m.OutputExtent
	bits := "Float32bits"
	if m.Dtype == "float64" {
		bits = "Float64bits"
	}
	var preflight strings.Builder
	preflight.Grow(4096 + len(m.OutputExtent)*4 + len(m.OutputData)*4 + len(m.InputData)*8)
	if m.InputData != "" && m.OutputData != "" && m.OutputGuard != "" {
		fmt.Fprintf(&preflight, "_input := append([]%s(nil),%s...)\n", m.Dtype, m.InputData)
		for _, arm := range []struct{ prefix, name string }{{"_s", serial}, {"_p", parallel}, {"_d", production}} {
			warmupResults := make([]string, len(results))
			names := make(map[string]string, len(results))
			for i := range warmupResults {
				warmupResults[i] = arm.prefix + strconv.Itoa(i)
				names[results[i]] = warmupResults[i]
			}
			fmt.Fprintf(&preflight, "%s := %s(%s)\n", strings.Join(warmupResults, ","), arm.name, strings.Join(args, ","))
			for _, i := range m.ErrorResults {
				fmt.Fprintf(&preflight, "if %s!=nil {b.Fatal(%s)}\n", warmupResults[i], warmupResults[i])
			}
			guard, err := replaceResultIdentifiers(m.OutputGuard, names)
			if err != nil {
				return nil, err
			}
			extent, err := replaceResultIdentifiers(m.OutputExtent, names)
			if err != nil {
				return nil, err
			}
			data, err := replaceResultIdentifiers(m.OutputData, names)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&preflight, "if !(%s) || %s != _n {b.Fatal(\"operation output shape differs\")}\n", guard, extent)
			fmt.Fprintf(&preflight, "%sInput := %s\nif len(%sInput)!=len(_input) {b.Fatal(\"operation changed input extent\")}\nfor _i:=range _input {if %s.%s(_input[_i])!=%s.%s(%sInput[_i]) {b.Fatal(\"operation changed observed input bits\")}}\n", arm.prefix, m.InputData, arm.prefix, aliases["math"], bits, aliases["math"], bits, arm.prefix)
			if arm.prefix == "_s" {
				fmt.Fprintf(&preflight, "_reference := append([]%s(nil),%s...)\n", m.Dtype, data)
			} else {
				fmt.Fprintf(&preflight, "%sData := %s\nfor _i:=range _reference {if %s.%s(_reference[_i])!=%s.%s(%sData[_i]) {b.Fatal(\"operation output bits differ from frozen serial reference\")}}\n", arm.prefix, data, aliases["math"], bits, aliases["math"], bits, arm.prefix)
			}
		}
	}
	policyParallel := strings.TrimPrefix(c.ParallelPolicy, m.PackagePath+".") + "(_dst,_src)"
	var postSelected strings.Builder
	postSelected.Grow(1024 + len(m.OutputData) + len(m.InputData))
	fmt.Fprintf(&postSelected, "_selectedData := %s; _selectedInput := %s\nif len(_selectedInput)!=len(_input) {b.Fatal(\"selected operation changed input extent\")}\nfor _i:=range _reference {if %s.%s(_reference[_i])!=%s.%s(_selectedData[_i]) {b.Fatal(\"selected operation output differs\")}}\nfor _i:=range _input {if %s.%s(_input[_i])!=%s.%s(_selectedInput[_i]) {b.Fatal(\"selected operation changed input bits\")}}", m.OutputData, m.InputData, aliases["math"], bits, aliases["math"], bits, aliases["math"], bits, aliases["math"], bits)
	if m.WorkerCallback {
		policyParallel = worker + "(_n,func(_lo,_hi int){ " + leaf + "(_dst[_lo:_hi],_src[_lo:_hi]) })"
	}
	fmt.Fprintf(&source, `func %s(t *%s.T) {
 _n,_err := %s.Atoi(%s.Getenv("PERFSCAN_CROSSOVER_SIZE")); if _err!=nil || _n<1 { t.Fatal("invalid observed shape request") }
 _fixed,_err := %s.Atoi(%s.Getenv("PERFSCAN_CROSSOVER_N")); if _err!=nil || _fixed<0 || _fixed==1 { t.Fatal("invalid measurement work request") }
 _arm := %s.Getenv("PERFSCAN_CROSSOVER_ARM"); if _arm!="serial" && _arm!="parallel" {t.Fatal("invalid requested policy arm")}
 _scope := %s.Getenv("PERFSCAN_CROSSOVER_SCOPE")
 var _benchmark func(*%s.B)
 switch _scope {
 case "policy":
  _benchmark = func(b *%s.B) {
   _src:=make([]%s,_n);_dst:=make([]%s,_n);_other:=make([]%s,_n)
   for _i:=range _src { _src[_i]=%s(_i&1023)-512 }
   _input:=append([]%s(nil),_src...)
   %s(_other,_src)
   for _i:=range _input {if %s.%s(_src[_i])!=%s.%s(_input[_i]) {b.Fatal("serial policy changed input bits")}}
   _reference:=append([]%s(nil),_other...)
   for _i:=range _dst {_dst[_i]=%s(%s.NaN())}
   %s
   for _i:=range _dst {if %s.%s(_dst[_i])!=%s.%s(_reference[_i]) || %s.%s(_src[_i])!=%s.%s(_input[_i]) {b.Fatal("observed policy outputs or input bits differ")}}
   b.ReportAllocs();b.ResetTimer()
   for range b.N {if _arm=="serial" {%s(_dst,_src)} else {%s}}
   %s.KeepAlive(_dst)
  }
 case "forced-operation", "production":
  _benchmark = func(b *%s.B) {
   %s := %s(_n)
   %s
   %s
   _call := %s
   if _scope=="forced-operation" {if _arm=="serial" {_call=%s} else {_call=%s}}
   %s := _call(%s)
   %s
   if !(%s) || %s != _n {b.Fatal("actual operation output extent differs from requested shape")}
   %s
   %s.KeepAlive(_r0)
   b.ReportAllocs();b.ResetTimer()
   for range b.N {
    %s = _call(%s)
    %s
    %s.KeepAlive(_r0)
   }
  }
 default: t.Fatal("unknown diagnostic scope")
 }
 _observation,_err := %s.Measure(_fixed,_benchmark);if _err!=nil {t.Fatal(_err)}
 _encoded,_err := %s.Marshal(_observation);if _err!=nil {t.Fatal(_err)}
 %s.Printf("%%s\n",_encoded)
}
`, diagnostic, aliases["testing"], aliases["strconv"], aliases["os"], aliases["strconv"], aliases["os"], aliases["os"], aliases["os"], aliases["testing"], aliases["testing"], m.Dtype, m.Dtype, m.Dtype, m.Dtype, m.Dtype, leaf, aliases["math"], bits, aliases["math"], bits, m.Dtype, m.Dtype, aliases["math"], policyParallel, aliases["math"], bits, aliases["math"], bits, aliases["math"], bits, aliases["math"], bits, leaf, policyParallel, aliases["runtime"], aliases["testing"], strings.Join(args, ","), factory, m.DtypeGuard, preflight.String(), production, serial, parallel, strings.Join(results, ","), strings.Join(args, ","), errorsCheck.String(), m.OutputGuard, output, postSelected.String(), aliases["runtime"], strings.Join(results, ","), strings.Join(args, ","), errorsCheck.String(), aliases["runtime"], aliases["github.com/jxsl13/perfscan/benchmarkevidence"], aliases["encoding/json"], aliases["fmt"])
	return format.Source([]byte(source.String()))
}
