package runner

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jxsl13/perfscan/perfscan/checks"
	"github.com/jxsl13/perfscan/perfscan/lint"
)

// TestFixNeverWritesGeneratedFile pins the runner's second-layer write-guard:
// even when -include-generated forces findings in a "// Code generated ... DO
// NOT EDIT." file to be REPORTED (so they reach the fix-apply stage), the write
// is REFUSED — the file stays byte-identical and stderr says why. filterGenerated
// (which drops such findings by default) is the first line of defense; this
// covers the case where a user deliberately opts past it with
// -include-generated, so a stringer/protoc/cgo output can never be silently
// rewritten by -fix. The existing tests cover the reporting filter and the
// detection unit, not this apply-stage guarantee.
func TestFixNeverWritesGeneratedFile(t *testing.T) {
	const src = `// Code generated by perfscan-test; DO NOT EDIT.

package p

import "sort"

func f(xs []int) {
	sort.Ints(xs)
}
`
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(diffGoMod), 0o644); err != nil {
		t.Fatal(err)
	}
	genPath := filepath.Join(dir, "gen.go")
	if err := os.WriteFile(genPath, []byte(src), 0o644); err != nil {
		t.Fatal(err)
	}

	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	defer func() { _ = os.Chdir(wd) }()

	var out, errBuf bytes.Buffer
	// -include-generated makes the sort.Ints finding REACH the apply stage; -fix
	// makes the runner attempt the write — the DO-NOT-EDIT guard must refuse it.
	Run(checks.All(), Options{
		Patterns:         []string{"./..."},
		MaxLevel:         lint.LevelAggressive,
		Fix:              true,
		IncludeGenerated: true,
		Stdout:           &out,
		Stderr:           &errBuf,
	})

	got, err := os.ReadFile(genPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != src {
		t.Errorf("the generated file was rewritten by -fix (it must stay byte-identical):\n%s", got)
	}
	if !strings.Contains(errBuf.String(), "generated file (DO NOT EDIT); not applied") {
		t.Errorf("expected the write-guard message on stderr, got:\n%s", errBuf.String())
	}
}
