package runner

import (
	"os"
	"path/filepath"
	"testing"

	"go/token"

	"github.com/jxsl13/perfscan/perfscan/lint"
)

// TestFilterGenerated covers the default skipping of findings in GENERATED Go
// files (the conventional `// Code generated ... DO NOT EDIT.` marker before
// the package clause, per go/ast.IsGenerated): by default such findings are
// dropped, -include-generated keeps them, an unparsable/missing file is
// treated as NOT generated (its findings are never silently swallowed), and a
// marker placed AFTER the package clause does not count as generated.
func TestFilterGenerated(t *testing.T) {
	dir := t.TempDir()

	genPath := filepath.Join(dir, "gen.go")
	if err := os.WriteFile(genPath, []byte(
		"// Code generated by tool; DO NOT EDIT.\n\npackage p\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	normalPath := filepath.Join(dir, "normal.go")
	if err := os.WriteFile(normalPath, []byte(
		"// Package p is hand-written.\npackage p\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Marker AFTER the package clause: ast.IsGenerated only honors the marker
	// before the package clause, so this file is NOT generated.
	latePath := filepath.Join(dir, "late.go")
	if err := os.WriteFile(latePath, []byte(
		"package p\n\n// Code generated by tool; DO NOT EDIT.\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	missingPath := filepath.Join(dir, "nope.go") // never created -> parse error

	mk := func(path string) Finding {
		return Finding{
			Check: &lint.Check{ID: "PS2101"},
			Pos:   token.Position{Filename: path, Line: 1},
		}
	}
	in := []Finding{mk(genPath), mk(normalPath), mk(latePath), mk(missingPath)}

	files := func(fs []Finding) []string {
		out := make([]string, 0, len(fs))
		for _, f := range fs {
			out = append(out, f.Pos.Filename)
		}
		return out
	}

	t.Run("default drops generated only", func(t *testing.T) {
		got := filterGenerated(in, false)
		want := []string{normalPath, latePath, missingPath}
		if len(got) != len(want) {
			t.Fatalf("got %d findings %v, want %d %v", len(got), files(got), len(want), want)
		}
		for i, w := range want {
			if got[i].Pos.Filename != w {
				t.Errorf("finding %d: got %s, want %s (order must be preserved)", i, got[i].Pos.Filename, w)
			}
		}
	})

	t.Run("include keeps everything", func(t *testing.T) {
		got := filterGenerated(in, true)
		if len(got) != len(in) {
			t.Fatalf("include=true: got %d findings %v, want all %d", len(got), files(got), len(in))
		}
		for i := range in {
			if got[i].Pos.Filename != in[i].Pos.Filename {
				t.Errorf("finding %d: got %s, want %s (order must be preserved)", i, got[i].Pos.Filename, in[i].Pos.Filename)
			}
		}
	})
}
