package runner

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
)

// forbiddenWriteRoots are directories perfscan must NEVER write a fix into:
//   - GOCACHE — the go-build cache, where cgo-PROCESSED translation units live
//     (their token.File.Name() is a cache path); writing there poisons a build
//     artifact instead of the user's source.
//   - GOMODCACHE — read-only dependency sources.
//   - GOROOT — the standard library (best-effort via $GOROOT; usually unset,
//     but stdlib writes fail on permissions anyway — GOCACHE is the real case).
//
// Computed once from the environment (with the documented defaults) so no
// subprocess is needed. Missing/empty roots are simply skipped.
var forbiddenWriteRoots = func() []string {
	var roots []string
	add := func(p string) {
		if p == "" {
			return
		}
		if abs, err := filepath.Abs(p); err == nil {
			roots = append(roots, filepath.Clean(abs))
		}
	}
	if c := os.Getenv("GOCACHE"); c != "" {
		add(c)
	} else if d, err := os.UserCacheDir(); err == nil {
		add(filepath.Join(d, "go-build"))
	}
	if m := os.Getenv("GOMODCACHE"); m != "" {
		add(m)
	} else {
		gp := os.Getenv("GOPATH")
		if gp == "" {
			if h, err := os.UserHomeDir(); err == nil {
				gp = filepath.Join(h, "go")
			}
		}
		if gp != "" {
			add(filepath.Join(gp, "pkg", "mod"))
		}
	}
	add(os.Getenv("GOROOT"))
	return roots
}()

// outsideWorkTree reports whether path lives under one of the forbiddenWriteRoots
// (build cache, module cache, GOROOT) — where a fix must never be written.
func outsideWorkTree(path string) bool {
	abs, err := filepath.Abs(path)
	if err != nil {
		return false
	}
	abs = filepath.Clean(abs)
	for _, root := range forbiddenWriteRoots {
		rel, err := filepath.Rel(root, abs)
		if err != nil {
			continue
		}
		// abs is under root iff the relative path does not escape upward.
		if rel != ".." && !hasDotDotPrefix(rel) {
			return true
		}
	}
	return false
}

func hasDotDotPrefix(rel string) bool {
	return len(rel) >= 3 && rel[0] == '.' && rel[1] == '.' && (rel[2] == filepath.Separator)
}

// generatedMarker matches the standard Go "this file is generated" line
// (https://go.dev/s/generatedcode): `// Code generated <by X>; DO NOT EDIT.`.
var generatedMarker = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// isGeneratedSource reports whether src is a generated Go file — it carries the
// conventional marker line before its package clause. cgo-processed TUs begin
// with "// Code generated by cmd/cgo; DO NOT EDIT.", so this also catches the
// cgo case content-side, independent of where the file lives.
func isGeneratedSource(src []byte) bool {
	for len(src) > 0 {
		var line []byte
		if i := bytes.IndexByte(src, '\n'); i >= 0 {
			line, src = src[:i], src[i+1:]
		} else {
			line, src = src, nil
		}
		t := bytes.TrimSpace(line)
		if bytes.HasPrefix(t, []byte("package ")) {
			return false // reached the package clause: not marked generated
		}
		if generatedMarker.Match(t) {
			return true
		}
	}
	return false
}
