package checks

// Runtime differential for PS2032: string(strconv.Append*(nil, ...))
// versus the direct strconv.Format*/Quote* rewrite. The fix's safety
// argument is that each strconv Append* function appends exactly the
// bytes its Format*/Quote* twin produces (the strconv docs state each
// Append* appends the string form "as generated by" its Format* twin),
// and string() of those bytes is that string byte-for-byte; appending to
// the LITERAL nil prepends nothing. This suite pins that claim over:
//
//   - all ten matched pairs (AppendInt/Uint/Float/Bool and the five
//     AppendQuote* variants against FormatInt/Uint/Float/Bool and
//     Quote*);
//   - integer edge values (0, ±1, the small-table boundaries 99/100,
//     MinInt64/MaxInt64, MaxUint64, powers of two) in EVERY legal base
//     2..36, plus randomized values with a fixed seed;
//   - float adversaries (±0, NaN, ±Inf, the smallest subnormal,
//     MaxFloat64/MaxFloat32, and floats built from random bit patterns)
//     crossed with every documented verb, an UNRECOGNIZED verb (both
//     sides render '%'+verb), precisions -1..40, and both bitSizes;
//   - quote adversaries (empty, quotes and backslashes, NUL, invalid
//     UTF-8, a lone surrogate, combining marks, 4 KiB, random byte
//     strings) and rune adversaries (negative, surrogate, 0x10FFFF,
//     out-of-range, unprintables);
//   - PANIC parity on illegal integer bases: both forms panic, with the
//     same message, raised by the shared formatter;
//   - the divergence the literal-nil gate excludes: a NON-nil (or
//     shadowed-nil) destination prepends its bytes, so those shapes are
//     never matched;
//   - the perf premise: FormatInt on the small-int table path is
//     allocation-free while the Before shape always allocates twice.

import (
	"fmt"
	"math"
	"math/rand"
	"strconv"
	"strings"
	"testing"
)

// ps2032Before*/ps2032After* are the exact Before/After shapes of the
// check for every matched pair.
func ps2032BeforeInt(x int64, b int) string   { return string(strconv.AppendInt(nil, x, b)) }
func ps2032AfterInt(x int64, b int) string    { return strconv.FormatInt(x, b) }
func ps2032BeforeUint(x uint64, b int) string { return string(strconv.AppendUint(nil, x, b)) }
func ps2032AfterUint(x uint64, b int) string  { return strconv.FormatUint(x, b) }
func ps2032BeforeFloat(f float64, m byte, p, s int) string {
	return string(strconv.AppendFloat(nil, f, m, p, s))
}
func ps2032AfterFloat(f float64, m byte, p, s int) string { return strconv.FormatFloat(f, m, p, s) }
func ps2032BeforeBool(v bool) string                      { return string(strconv.AppendBool(nil, v)) }
func ps2032AfterBool(v bool) string                       { return strconv.FormatBool(v) }

func TestEquiv_PS2032_Integers(t *testing.T) {
	values := []int64{
		0, 1, -1, 9, -9, 10, -10, 35, 36, 37, 99, 100, -99, -100,
		math.MinInt64, math.MaxInt64, math.MinInt64 + 1, math.MaxInt64 - 1,
		1 << 32, -(1 << 32), 1<<62 - 1, -1 << 62,
	}
	rng := rand.New(rand.NewSource(0x2032))
	for range 2000 {
		values = append(values, rng.Int63()-rng.Int63())
	}
	for _, x := range values {
		for base := 2; base <= 36; base++ {
			if got, want := ps2032BeforeInt(x, base), ps2032AfterInt(x, base); got != want {
				t.Fatalf("AppendInt(%d, base %d) diverges: before=%q after=%q", x, base, got, want)
			}
		}
	}
	uvalues := []uint64{0, 1, 9, 10, 99, 100, math.MaxUint64, math.MaxUint64 - 1, 1 << 63, 1<<64 - 2}
	for range 2000 {
		uvalues = append(uvalues, rng.Uint64())
	}
	for _, x := range uvalues {
		for base := 2; base <= 36; base++ {
			if got, want := ps2032BeforeUint(x, base), ps2032AfterUint(x, base); got != want {
				t.Fatalf("AppendUint(%d, base %d) diverges: before=%q after=%q", x, base, got, want)
			}
		}
	}
}

func TestEquiv_PS2032_Floats(t *testing.T) {
	floats := []float64{
		0, math.Copysign(0, -1), 1, -1, 0.5, 1.5, math.Pi,
		math.NaN(), math.Inf(1), math.Inf(-1),
		math.SmallestNonzeroFloat64, math.SmallestNonzeroFloat32,
		math.MaxFloat64, math.MaxFloat32, 1e-310, // subnormal
		123456789.123456789, -123.456e77, 5e-324,
	}
	rng := rand.New(rand.NewSource(0x2032))
	for range 3000 {
		floats = append(floats, math.Float64frombits(rng.Uint64()))
	}
	// 'z' is not a recognized verb: both sides render "%z" identically.
	verbs := []byte{'b', 'e', 'E', 'f', 'g', 'G', 'x', 'X', 'z'}
	precs := []int{-1, 0, 1, 2, 7, 17, 40}
	for _, f := range floats {
		for _, m := range verbs {
			for _, p := range precs {
				for _, s := range []int{32, 64} {
					if got, want := ps2032BeforeFloat(f, m, p, s), ps2032AfterFloat(f, m, p, s); got != want {
						t.Fatalf("AppendFloat(%v, %q, %d, %d) diverges: before=%q after=%q", f, m, p, s, got, want)
					}
				}
			}
		}
	}
	for _, v := range []bool{true, false} {
		if got, want := ps2032BeforeBool(v), ps2032AfterBool(v); got != want {
			t.Fatalf("AppendBool(%v) diverges: before=%q after=%q", v, got, want)
		}
	}
}

func TestEquiv_PS2032_Quotes(t *testing.T) {
	strs := []string{
		"", "a", " ", `he said "hi"`, "back\\slash", "\x00", "a\x00b",
		"\xff\xfe\x80",       // invalid UTF-8 — both sides escape byte-wise
		string(rune(0xD800)), // lone surrogate encodes as RuneError
		"\ufeff\u200b",       // non-graphic zero-width marks
		"héllo, 世界", "\U0001F600", "é", "tab\tnl\ncr\r",
		strings.Repeat("q\"", 2048), // 4 KiB with embedded quotes
	}
	rng := rand.New(rand.NewSource(0x2032))
	for range 1000 {
		b := make([]byte, rng.Intn(64))
		rng.Read(b)
		strs = append(strs, string(b))
	}
	for _, s := range strs {
		if got, want := string(strconv.AppendQuote(nil, s)), strconv.Quote(s); got != want {
			t.Fatalf("AppendQuote(%q) diverges: before=%q after=%q", s, got, want)
		}
		if got, want := string(strconv.AppendQuoteToASCII(nil, s)), strconv.QuoteToASCII(s); got != want {
			t.Fatalf("AppendQuoteToASCII(%q) diverges: before=%q after=%q", s, got, want)
		}
		if got, want := string(strconv.AppendQuoteToGraphic(nil, s)), strconv.QuoteToGraphic(s); got != want {
			t.Fatalf("AppendQuoteToGraphic(%q) diverges: before=%q after=%q", s, got, want)
		}
	}
	runes := []rune{
		'a', '"', '\'', '\\', 0, ' ', '\t', 0x7F, 0x80,
		-1, 0xD800, 0xDFFF, // invalid: both sides emit RuneError
		0x10FFFF, 0x110000, // max valid and out of range
		0x1F600, 0x200B, 0xFFFD,
	}
	for range 2000 {
		// Spans negatives, the surrogate range, and past 0x10FFFF.
		runes = append(runes, rune(rng.Intn(0x140000)-0x10000))
	}
	for _, r := range runes {
		if got, want := string(strconv.AppendQuoteRune(nil, r)), strconv.QuoteRune(r); got != want {
			t.Fatalf("AppendQuoteRune(%d) diverges: before=%q after=%q", r, got, want)
		}
		if got, want := string(strconv.AppendQuoteRuneToASCII(nil, r)), strconv.QuoteRuneToASCII(r); got != want {
			t.Fatalf("AppendQuoteRuneToASCII(%d) diverges: before=%q after=%q", r, got, want)
		}
		if got, want := string(strconv.AppendQuoteRuneToGraphic(nil, r)), strconv.QuoteRuneToGraphic(r); got != want {
			t.Fatalf("AppendQuoteRuneToGraphic(%d) diverges: before=%q after=%q", r, got, want)
		}
	}
}

// TestEquiv_PS2032_PanicParity pins that both forms panic identically on
// an illegal integer base — the panic is raised by the formatter both
// call, so the rewrite changes neither the panic nor its message.
func TestEquiv_PS2032_PanicParity(t *testing.T) {
	capture := func(f func()) (msg string, panicked bool) {
		defer func() {
			if v := recover(); v != nil {
				msg, panicked = fmt.Sprint(v), true
			}
		}()
		f()
		return "", false
	}
	for _, base := range []int{-1, 0, 1, 37, 1000} {
		bm, bp := capture(func() { _ = ps2032BeforeInt(5, base) })
		am, ap := capture(func() { _ = ps2032AfterInt(5, base) })
		if bp != ap || bm != am {
			t.Fatalf("int base %d panic parity broken: before (%v, %q) after (%v, %q)", base, bp, bm, ap, am)
		}
		if !bp {
			t.Fatalf("int base %d: expected both forms to panic", base)
		}
		bm, bp = capture(func() { _ = ps2032BeforeUint(5, base) })
		am, ap = capture(func() { _ = ps2032AfterUint(5, base) })
		if bp != ap || bm != am {
			t.Fatalf("uint base %d panic parity broken: before (%v, %q) after (%v, %q)", base, bp, bm, ap, am)
		}
	}
}

// TestEquiv_PS2032_NonNilDestinationDivergence pins the divergence the
// literal-nil gate excludes: a destination that already holds bytes —
// including a SHADOWED identifier named nil — prepends them, so the
// check matches only the predeclared nil.
func TestEquiv_PS2032_NonNilDestinationDivergence(t *testing.T) {
	buf := []byte("seed")
	if got := string(strconv.AppendInt(buf, 42, 10)); got == strconv.FormatInt(42, 10) {
		t.Fatalf("AppendInt to a non-empty buffer unexpectedly equals FormatInt: %q", got)
	} else if got != "seed42" {
		t.Fatalf("AppendInt(seed, 42, 10) = %q, want %q", got, "seed42")
	}
	nil := []byte("seed") //nolint:all — deliberately shadows the predeclared nil, the exact hazard the gate rejects
	if got := string(strconv.AppendInt(nil, 42, 10)); got != "seed42" {
		t.Fatalf("AppendInt(shadowed nil, 42, 10) = %q, want %q", got, "seed42")
	}
}

// TestEquiv_PS2032_AfterAllocProfile pins the perf premise: the Before
// shape always pays the append-from-nil allocation PLUS the string
// conversion's copy; the After shape allocates at most once, and on
// FormatInt's small-integer table path (0 <= i < 100, base 10) not at
// all.
func TestEquiv_PS2032_AfterAllocProfile(t *testing.T) {
	var sink string
	if avg := testing.AllocsPerRun(200, func() { sink = ps2032AfterInt(7, 10) }); avg != 0 {
		t.Errorf("strconv.FormatInt(7, 10) allocates %v times per run, want 0 (small-int table path)", avg)
	}
	if avg := testing.AllocsPerRun(200, func() { sink = ps2032AfterInt(123456, 10) }); avg > 1 {
		t.Errorf("strconv.FormatInt(123456, 10) allocates %v times per run, want <= 1", avg)
	}
	if avg := testing.AllocsPerRun(200, func() { sink = ps2032BeforeInt(123456, 10) }); avg < 2 {
		t.Logf("string(strconv.AppendInt(nil, 123456, 10)) allocates %v times per run — the compiler learned to elide one; the win claim may need re-framing", avg)
	}
	_ = sink
}
